const TEST = {
    LOAD: 'IMAGES_LOAD',
    LOAD_SUCCESS: 'IMAGES_LOAD_SUCCESS',
    LOAD_FAIL: 'IMAGES_LOAD_FAIL',
};

const USER = {
    NOGRANTED: 'NOGRANTED',
    AUTH: 'AUTH_USER',
    SAGA_AUTH: 'AUTH_BY_SAGA',
    SAGA_LOGIN: 'LOGIN_SUBMIT',
    UPDATEUSER: 'UPDATEUSER',
    UPDATERR: 'UPDATERR',
    PAGELOADING: 'PAGELOADING',
    PAGEVALIDATING: 'PAGEVALIDATING'
};

export { USER, TEST };
